apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingressroute-certificate
  namespace: argocd
spec:
  secretName: argocd-certificate-secret
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - argocd.k8s.conciflex.com.br

