helm upgrade --install traefik traefik/traefik -n traefik \
  --create-namespace \
  --set replicas=2 \
  --set service.type=LoadBalancer \
  --set service.annotations."oci\.oraclecloud\.com/load-balancer-subnet-ids"='["ocid1.subnet.oc1.sa-saopaulo-1.aaaaaaaaftghvf3fiuvogxgn2vk4qf2im7iu4hyieblosbxvsj4p7tohd6ya"]' \
  --set service.annotations."oci\.oraclecloud\.com/load-balancer-type"="public" \
  --set ports.web.port=8000 \
  --set ports.websecure.port=8443 \
  --set service.ports.web=80 \
  --set service.ports.websecure=443 \
  --set logs.general.level=INFO \
  --set logs.access.enabled=true \
  --set entryPoints.web.http.redirections.entryPoint.to=websecure \
  --set entryPoints.web.http.redirections.entryPoint.scheme=https \
  --set entryPoints.web.http.redirections.entryPoint.permanent=true

