helm upgrade --install traefik traefik/traefik -n traefik \
  --create-namespace \
  --set replicas=2 \
  --set service.type=LoadBalancer \
  --set service.annotations."oci\.oraclecloud\.com/load-balancer-subnet-ids"="\[\"ocid1.subnet.oc1.sa-saopaulo-1.aaa...\"\]" \
  --set service.annotations."oci\.oraclecloud\.com/load-balancer-type"="public" \
  --set ports.web.port=80 \
  --set ports.websecure.port=443 \
  --set logs.general.level=INFO \
  --set logs.access.enabled=true